// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzfwmftpyxjtdohxhcgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6ZndtZnRweXhqdGRvaHhoY2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODQ0MDMsImV4cCI6MjA2NTQ2MDQwM30.6S2XmWyoi86C0FbokxmtJ4kwTQB_djJdfvgD6MDjBeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);